name: Lint and Build test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4.2.2

            - name: Setup pnpm
              uses: pnpm/action-setup@v4.1.0

            - name: Setup Node.js
              uses: actions/setup-node@v4.4.0
              with:
                  node-version-file: .node-version
                  cache: pnpm

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Check code for linting & formatting issues
              run: pnpm check:ci

            - name: Try to build the project
              run: pnpm build